### ISSUE TITLE
sidebar problems

### ISSUE THREAD

**Issue by oarashi** [jazzsequence/museum-core#81]
Hi! Thanks for awesome theme. 
I have some problems with sidebar. Currently I'm using Polylang plugin and if I turn on english language everything works good (I can edit sidebar), but when I turn on other languages version page sidebar disappears from setting. (footer sidebar shows in all languages)
https://monosnap.com/file/AY8Xzodn0YQigtpxDSKQtFWzMLXOAD
https://monosnap.com/file/AY8Xzodn0YQigtpxDSKQtFWzMLXOAD
Can you please help me with this issue? Thanks!

=======

I've changed functions.php in this way:
`register_sidebar(array(
            'id' => 'main-sidebar-box',
        	'name' => __('Sidebar','museum-core'),
        	'description' => __('This is the regular, widgetized sidebar','museum-core'),
            'before_widget' => '<li id="%1$s" class="widget %2$s">',
            'after_widget' => '</li>',
            'before_title' => '<h3 class="widgettitle">',
            'after_title' => '</h3>'
        ));`
And then changed sidebar.php
`<ul>
         <?php dynamic_sidebar( 'main-sidebar-box'); ?>
     </ul>`

**Comment by jazzsequence** [comment]
Good call. I've requested changes on your PRs to combine them into one PR (and cancel the other) and then I'll merge it in.

**Comment by jazzsequence** [comment]
fixes #79

**Comment by jazzsequence** [comment]
fixed by #84
